name: Build Python Executable

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch (change if needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest  # Use Windows because pyinstaller creates .exe files

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'  # Specify the Python version you're using

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # Install pyinstaller for building the executable

      # Step 4: Build the executable using PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name=EFOD-Helper main.py

      # Step 5: Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: EFOD-Helper-executable
          path: dist/EFOD-Helper.exe  # Path to the generated .exe file